In [33]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.11.0'

In [7]:
torch.empty(2,2,3)

tensor([[[-2.9059e+04,  3.0892e-41, -2.8946e+04],
         [ 3.0892e-41,  2.0688e-36,  4.5821e-41]],

        [[ 9.1084e-44,  0.0000e+00, -8.0226e+02],
         [ 3.0892e-41,  6.8664e-44,  0.0000e+00]]])

In [8]:
torch.rand(2,2)

tensor([[0.0460, 0.3892],
        [0.1187, 0.9269]])

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(3,4,dtype=torch.int)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [13]:
torch.ones(3,4,dtype=torch.double)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [14]:
torch.ones(3,4,dtype=torch.float16)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float16)

In [16]:
t = torch.rand(2,3)
t.size(), t.dtype

(torch.Size([2, 3]), torch.float32)

In [17]:
torch.tensor([2.5,8,1.26])

tensor([2.5000, 8.0000, 1.2600])

In [21]:
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)
print(t1)
print(t2)

tensor([[0.8543, 0.3301],
        [0.4345, 0.3987]])
tensor([[0.7809, 0.8343],
        [0.4596, 0.4434]])


In [22]:
ad = t1 + t2
print(ad)
torch.add(t1,t2)

tensor([[1.6353, 1.1644],
        [0.8941, 0.8421]])


tensor([[1.6353, 1.1644],
        [0.8941, 0.8421]])

In [34]:
t1.add_(t2) # inplace addition for t1

tensor([[2.4162, 1.9987],
        [1.3537, 1.2855]])

In [35]:
ad[1,1]

tensor(0.8421)

In [36]:
ad.view(4) # reshape the tensor

tensor([1.6353, 1.1644, 0.8941, 0.8421])

In [37]:
ad.view(-1,4).size(), ad.view(4).size()

(torch.Size([1, 4]), torch.Size([4]))

In [38]:
t3 = torch.ones(5)
arr = t3.numpy()

In [39]:
arr

array([1., 1., 1., 1., 1.], dtype=float32)

In [42]:
t3.add_(1),arr # When we are using the CPU instead of GPU since both variables are sharing the same memory changes in one would affect the other one

(tensor([3., 3., 3., 3., 3.]), array([3., 3., 3., 3., 3.], dtype=float32))

In [44]:
torch.from_numpy(np.ones(5))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

- Does PyTorch see any GPUs?	`torch.cuda.is_available()`
- Are tensors stored on GPU by default?	`torch.rand(10).device`
- Set default tensor type to CUDA:	`torch.set_default_tensor_type(torch.cuda.FloatTensor)`
- Is this tensor a GPU tensor?	`my_tensor.is_cuda`
- Is this model stored on the GPU?	`all(p.is_cuda for p in my_model.parameters())`

In [47]:
# Check for availablity of CUDA to use GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("There is GPU to use")
    print(f"Number of GPUs:{torch.cuda.device_count()}")
    print(f"GPU name is:{torch.cuda.get_device_name(0)}")

There is GPU to use
Number of GPUs:1
GPU name is:TITAN Xp


In [48]:
t3.device

device(type='cpu')

In [51]:
t3_gpu = t3.to(device)

In [52]:
t3_gpu.device

device(type='cuda', index=0)

In [53]:
torch.set_default_tensor_type(torch.cuda.FloatTensor)

In [54]:
t4 = torch.ones(3,5)

In [55]:
t4.device

device(type='cuda', index=0)

In [57]:
t4.numpy() # Error is due to have data in GPU and numpy is able to access the data in CPU memory

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [59]:
t4.to("cpu").numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)