In [1]:
import torch
import numpy as np

In [2]:
torch.set_default_tensor_type(torch.cuda.FloatTensor)

In [3]:
t1 = torch.rand(3, requires_grad=True)

In [4]:
t1

tensor([0.3921, 0.5682, 0.1831], requires_grad=True)

In [5]:
t2 = t1 + 2
t2

tensor([2.3921, 2.5682, 2.1831], grad_fn=<AddBackward0>)

In [9]:
t3 = t2*t2*3
t3

tensor([17.1658, 19.7873, 14.2976], grad_fn=<MulBackward0>)

In [10]:
t3 = t3.mean()
t3

tensor(17.0836, grad_fn=<MeanBackward0>)

In [12]:
t3.backward()

In [14]:
t1.grad

tensor([4.7841, 5.1364, 4.3662])

In [17]:
t1.grad

tensor([4.7841, 5.1364, 4.3662])

In [76]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

In [77]:
# Forward pass
y_hat = x * w
loss = (y_hat - y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [78]:
# backward pass
loss.backward()
print(w.grad) # update the weights based on the grad

tensor(-2.)
